insert into public.tasks(title,owner,stream,anchor,at_n,hard,note) values
('Agree your operating rhythm: 30-min weekly check-in and who owns which workstream','both','us','week',14,false,'See the playbook. One owner per task; ''Both'' only for genuine joint decisions.'),
('Flu vaccine','me','health','week',14,false,'Offered free at any stage of pregnancy during the autumn/winter season (GP, pharmacy or maternity unit).'),
('Get a maternity exemption certificate (MatEx)','me','health','week',15,false,'Free NHS prescriptions and dental care during pregnancy and for 12 months after. Ask your midwife for form FW8.'),
('Map the mixed care pathway: what is NHS, what is private, and the costs','both','health','week',15,false,'Private scans, consultant, birth location. Confirm who holds your notes and how private results reach the NHS team.'),
('Confirm 20-week anomaly scan date and book leave for both','me','health','week',16,false,'Scan is done between 18+0 and 20+6 weeks.'),
('Read both employers'' family-leave policies','both','work','week',16,false,'Enhanced maternity/paternity pay, clawback clauses, KIT days, return terms.'),
('Build the leave-period household budget','partner','work','week',16,false,'Statutory Maternity Pay: 6 weeks at 90% of average weekly earnings, then 33 weeks at £194.32 or 90% if lower (2026/27 rate). Add any employer top-up.'),
('Book antenatal classes (NHS free sessions plus any private course)','partner','birth','week',17,false,'Private courses for ~30–34 weeks fill early.'),
('Whooping cough vaccine','me','health','week',20,false,'Offered from 16 weeks; best given around the 20-week scan.'),
('Decide maternity leave start date and length','both','work','week',20,false,'Earliest start is 11 weeks before the expected week of childbirth.'),
('Shortlist, visit and join nursery waiting lists','partner','childcare','week',20,false,'London waiting lists can run a year or more.'),
('Collect MATB1 certificate and send it to HR','me','work','week',21,false,'Midwife or GP can issue it from 20 weeks.'),
('Tell your employer: pregnancy, due week and leave start date','me','work','week',22,true,'Legal deadline is the end of the 15th week before the expected week of childbirth (about week 25). Target week 22 for buffer.'),
('Give paternity leave notice to employer','partner','work','week',22,true,'Notice due 15 weeks before the expected week of childbirth. Leave is a day-one right; can be taken as two 1-week blocks within 52 weeks of birth. Paternity pay still needs 26 weeks'' service.'),
('Plan the baby''s sleep space for the first six months','both','home','week',22,false,'Safer-sleep guidance: baby sleeps in your room, on a firm flat mattress.'),
('Plan protected time together before the third trimester','both','us','week',22,false,'Airline cut-offs for travel in late pregnancy vary; check before booking.'),
('Big-kit decisions: pram, car seat, cot or Moses basket','both','home','week',24,false,'Decide buy, borrow or second-hand. Car seats: buy new or from a trusted source only.'),
('Check funded childcare and Tax-Free Childcare eligibility','partner','childcare','week',24,false,'Working-parent 30 hours runs from the term after baby turns 9 months; each parent must earn at least the minimum threshold and have adjusted net income of £100k or less.'),
('Wills, guardians and life insurance','partner','admin','week',24,false,'If unmarried, check parental responsibility rules for birth registration.'),
('24–28 week tests if offered (e.g. glucose tolerance test)','me','health','week',24,false,''),
('Work handover plan and cover discussion with manager','me','work','week',26,false,''),
('RSV vaccine','me','health','week',28,false,'Offered from 28 weeks; soonest after 28 weeks gives the baby most protection.'),
('28-week appointment and bloods','me','health','week',28,false,'Anti-D is offered if you are rhesus negative.'),
('Learn perinatal mental health warning signs, for both parents','both','us','week',30,false,'Agree now how either of you will raise concerns, and who to call (GP, midwife, health visitor).'),
('Tour the birth unit; plan route, parking and timing','partner','birth','week',32,false,''),
('Buy and fit car seat; practise installing it','partner','home','week',32,false,''),
('Postnatal support plan: helpers, visitor rules, meal rota','both','us','week',32,false,''),
('Infant feeding preparation','me','birth','week',32,false,'Class or session with a feeding specialist; decide what kit you need.'),
('Assemble cot or crib and buy a firm flat mattress','partner','home','week',33,false,''),
('Write birth preferences together and discuss with your midwife or obstetrician','both','birth','week',34,false,'Include pain relief, feeding, and what you''d want if plans change.'),
('Cook and freeze 10–15 meals','partner','home','week',34,false,''),
('Wash baby clothes and set up a changing station','partner','home','week',34,false,''),
('Paperwork folder: notes, MATB1 copy, insurance, ID for registration','partner','admin','week',34,false,''),
('Pack hospital bags (you, baby, partner)','both','birth','week',36,false,''),
('Labour logistics: who to call, when to go in, home cover','partner','birth','week',36,false,'Write key numbers on paper as well as phones.'),
('Last working day, out-of-office and KIT-day agreement','me','work','week',36,false,'Up to 10 keeping-in-touch days, by agreement.'),
('Confirm partner''s leave dates and handover','partner','work','week',36,false,''),
('Stock up: nappies, wipes, maternity pads, night lights','partner','home','week',37,false,''),
('Clear the calendar from week 38','both','us','week',38,false,''),
('Newborn blood spot (heel prick) test','both','health','birth',5,false,'Usually done by the midwife around day 5.'),
('Couple check-in: night shifts and task rebalance','both','us','birth',7,false,''),
('Health visitor new-birth visit','both','health','birth',12,false,'Usually 10–14 days after birth.'),
('Register baby with your GP','partner','admin','birth',14,false,''),
('Plan partner''s second paternity leave block, if taking one','partner','work','birth',14,false,''),
('Register the birth','partner','admin','birth',30,true,'Legal deadline in England: within 42 days. Target 30 days for buffer.'),
('Claim Child Benefit','partner','admin','birth',35,false,'Claims backdate up to 3 months. Claim even if you opt out of payments, so the child gets a National Insurance number.'),
('6–8 week postnatal check (you) and baby check','me','health','birth',42,false,''),
('Book 8-week vaccinations','partner','health','birth',50,false,'Given at 8, 12 and 16 weeks.'),
('Update wills and add baby to insurance, if not done','partner','admin','birth',60,false,''),
('Apply for your childcare funding code','partner','childcare','birth',161,false,'Apply up to 16 weeks before baby turns 9 months; deadline is the day before the term you want funding to start.'),
('Return-to-work plan and any flexible working request','me','work','birth',180,false,'Flexible working requests are a day-one right.');
insert into public.items(name,zone,qty,owner,essential,note) values
('Bedside crib or Moses basket','bedroom',1,'partner',true,'Safer sleep: baby sleeps in your room for the first 6 months.'),
('Firm, flat, waterproof crib mattress','bedroom',1,'partner',true,'Buy new and check it fits the crib with no gaps.'),
('Fitted crib sheets','bedroom',4,'partner',true,''),
('Baby sleeping bags (0–6m, seasonal TOG)','bedroom',3,'partner',true,'No pillows, duvets or bumpers.'),
('Room thermometer','bedroom',1,'partner',true,'Aim for a room of about 16–20°C.'),
('Dim night light','bedroom',1,'partner',true,''),
('Blackout blind','bedroom',1,'partner',false,''),
('Baby monitor','bedroom',1,'partner',false,''),
('Changing mats','changing',2,'partner',true,'One upstairs, one downstairs.'),
('Newborn nappies (size 1)','changing',2,'partner',true,'Packs; don''t overbuy one size.'),
('Water wipes or cotton wool','changing',4,'partner',true,''),
('Nappy cream','changing',1,'partner',true,''),
('Lidded nappy bin','changing',1,'partner',true,''),
('Muslin cloths','changing',12,'partner',true,''),
('Nappy sacks','changing',1,'partner',true,''),
('Baby bath or bath support','bathroom',1,'partner',false,'Topping-and-tailing is fine for the first weeks.'),
('Hooded towels','bathroom',2,'partner',true,''),
('Soft washcloths','bathroom',6,'partner',true,''),
('Nursing bras','feeding',3,'me',true,'Get fitted from about 36 weeks.'),
('Breast pads','feeding',2,'me',true,''),
('Nipple cream','feeding',1,'me',true,''),
('Feeding pillow','feeding',1,'me',false,''),
('Breast pump','feeding',1,'me',false,'Decide after feeding preparation session.'),
('Bottles','feeding',4,'partner',false,'If expressing or using formula.'),
('Steriliser','feeding',1,'partner',false,'If using bottles.'),
('Bottle brush','feeding',1,'partner',false,''),
('Rear-facing i-Size car seat','out',1,'partner',true,'Buy new or from a trusted source; fit by week 32.'),
('Pram or travel system','out',1,'both',true,'Joint decision if over the spending threshold.'),
('Changing bag','out',1,'partner',true,''),
('Sling or carrier','out',1,'both',false,'Try before buying; follow T.I.C.K.S. guidance.'),
('Pram rain cover','out',1,'partner',true,''),
('Vests (newborn and 0–3m)','clothing',8,'partner',true,''),
('Sleepsuits (newborn and 0–3m)','clothing',8,'partner',true,''),
('Hats','clothing',2,'partner',true,''),
('Cardigans or jackets','clothing',2,'partner',true,''),
('Socks and scratch mittens','clothing',4,'partner',true,''),
('Maternity pads','postpartum',3,'me',true,'Packs.'),
('Soft high-waisted knickers','postpartum',6,'me',true,''),
('Peri bottle','postpartum',1,'me',true,''),
('Pain relief agreed with your midwife','postpartum',1,'me',true,''),
('Front-opening nightwear','postpartum',2,'me',true,''),
('Digital baby thermometer','safety',1,'partner',true,''),
('Smoke and CO alarms tested','safety',1,'partner',true,''),
('First aid kit','safety',1,'partner',true,'');
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Night-feed caddy','Bedside',34,0) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Water bottle','',0),('Snacks','',1),('Long phone charger','',2),('Muslins','3',3),('Breast pads','',4),('Nipple cream','',5),('Night light','',6),('Spare vest and sleepsuit','',7),('Nappies and wipes','4',8)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Downstairs nappy caddy','Living room',34,1) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Nappies','10',0),('Wipes','',1),('Nappy cream','',2),('Portable changing mat','',3),('Nappy sacks','',4),('Spare vest and sleepsuit','',5),('Muslins','2',6),('Hand sanitiser','',7)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Upstairs changing station','Bedroom',34,2) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Nappies','20',0),('Wipes','',1),('Nappy cream','',2),('Changing mat','',3),('Nappy bin','',4),('Muslins','4',5),('Spare clothes','',6)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Hospital bag: Tem','Hallway',36,3) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Maternity notes and birth preferences','',0),('Front-opening nightwear','2',1),('Maternity pads','2 packs',2),('Soft knickers','6',3),('Nursing bras','2',4),('Breast pads','',5),('Toiletries and lip balm','',6),('Snacks and drinks','',7),('Long phone charger','',8),('Going-home outfit','',9),('Glasses or contacts','',10)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Hospital bag: baby','Hallway',36,4) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Vests','4',0),('Sleepsuits','4',1),('Hat','',2),('Scratch mittens','',3),('Muslins','3',4),('Newborn nappies','1 pack',5),('Wipes or cotton wool','',6),('Blanket','',7),('Going-home outfit','',8),('Car seat fitted in car','',9)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Hospital bag: partner','Hallway',36,5) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Snacks','',0),('Change of clothes','',1),('Phone charger','',2),('Toiletries','',3),('Card for parking','',4),('Pillow','',5),('List of who to call','',6)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Postpartum recovery caddy','Bathroom',36,6) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Maternity pads','',0),('Peri bottle','',1),('Soft knickers','',2),('Pain relief agreed with midwife','',3),('Water bottle','',4),('Nipple cream','',5)) v(l,q,s);
with c as (insert into public.caddies(name,location,ready_by_week,sort) values ('Changing bag','Hallway',37,7) returning id)
insert into public.caddy_items(caddy_id,label,qty,sort) select c.id,v.l,v.q,v.s from c, (values ('Nappies','4',0),('Wipes','',1),('Portable changing mat','',2),('Nappy sacks','',3),('Spare outfit','',4),('Muslins','2',5),('Hand sanitiser','',6)) v(l,q,s);
insert into public.settings(id) values (1);
